export const IMAGE_SECTION: string = "IMAGE_SECTION";
export const PARTICIPANT_SECTION: string = "PARTICIPANT_SECTION";
export const CEREMONY_SECTION: string = "CEREMONY_SECTION";
export const RECEPTION_SECTION: string = "RECEPTION_SECTION";
